name: "Terraform Deployment"

on:
  push:
    branches:
      - main
    paths:
      - 'TF-Core/**'
  pull_request:
    paths:
      - 'TF-Core/**'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
jobs:
  terraform:
    name: "Terraform Deployment!"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./TF-Core
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform init
        id: tf-init
        run: terraform init
      - name: Terraform validate
        id: tf-validate
        run: terraform validate -no-color
      - name: Terraform Plan
        id: tf-plan
        run: terraform plan -no-color
        continue-on-error: true
      - name: Terraform Apply
        id: tf-apply
        if: ${{ github.event.pull_request.merged == true }}
        run: terraform apply --auto-approve -input=false

          

      